# Generated by Django 4.2.5 on 2023-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0002_alter_userprofile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(choices=[('cricket_bat', 'Cricket Bat'), ('ball', 'Ball'), ('shoe', 'Shoe'), ('jersey', 'Jersey')], max_length=100)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
