# Generated by Django 4.2.5 on 2023-09-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0004_remove_product_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
