# Generated by Django 4.2.5 on 2023-09-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0005_product_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
    ]
