# Generated by Django 4.2.5 on 2023-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0006_remove_product_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
