# Generated by Django 4.2.5 on 2023-09-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0008_remove_product_year_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
