# Generated by Django 4.2.5 on 2023-09-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0010_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
