# Generated by Django 4.2.5 on 2023-09-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0011_product_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_custom',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
