# Generated by Django 4.2.5 on 2023-09-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0012_remove_product_is_custom_userprofile_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
