# Generated by Django 4.2.5 on 2023-09-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisport', '0013_userprofile_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('tennis', 'Tennis'), ('others', 'Others')], default='cricket', max_length=20),
        ),
    ]
